class SmartSchoolException(Exception): ...

class SmartschoolAuthenticationError(SmartSchoolException): ...

class SmartschoolParsingError(SmartSchoolException):
    """Indicates an error occurred while parsing data from Smartschool."""
    pass

class DownloadError(SmartSchoolException): ...
